/*
 * Created on 2022-04-27 ( 21:21:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persitence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "CourseProgress"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Course_Progress", schema = "dbo", catalog = "${bezkoder.app.databaseName}")
public class CourseProgress implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Integer id;

    // --- ENTITY DATA FIELDS
    @Column(name = "ID_Faculty", nullable = false, length = 50)
    private String idFaculty;

    @Column(name = "ID_Course", nullable = false, length = 50)
    private String idCourse;

    @Column(name = "number_year")
    private Integer numberYear;

    @Column(name = "optional")
    private Boolean optional;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name = "ID_Faculty", referencedColumnName = "ID_Faculty", insertable = false, updatable = false)
    private Faculty faculty;

    @ManyToOne
    @JoinColumn(name = "ID_Course", referencedColumnName = "ID_Course", insertable = false, updatable = false)
    private Course course;

    /**
     * Constructor
     */
    public CourseProgress() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setIdFaculty(String idFaculty) {
        this.idFaculty = idFaculty;
    }

    public String getIdFaculty() {
        return this.idFaculty;
    }

    public void setIdCourse(String idCourse) {
        this.idCourse = idCourse;
    }

    public String getIdCourse() {
        return this.idCourse;
    }

    public void setNumberYear(Integer numberYear) {
        this.numberYear = numberYear;
    }

    public Integer getNumberYear() {
        return this.numberYear;
    }

    public void setOptional(Boolean optional) {
        this.optional = optional;
    }

    public Boolean getOptional() {
        return this.optional;
    }

    // --- GETTERS FOR LINKS
    public Faculty getFaculty() {
        return this.faculty;
    }

    public Course getCourse() {
        return this.course;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(id);
        sb.append("|");
        sb.append(idFaculty);
        sb.append("|");
        sb.append(idCourse);
        sb.append("|");
        sb.append(numberYear);
        sb.append("|");
        sb.append(optional);
        return sb.toString();
    }

}
