/*
 * Created on 2022-04-27 ( 11:09:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persitence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "DateExam"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Date_Exam", schema = "dbo", catalog = "shegga_course_register" )
public class DateExam implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Integer id;

    // --- ENTITY DATA FIELDS
    @Column(name = "ID_Semester", nullable = false, length = 50)
    private String idSemester;


    @Column(name = "ID_Schedule", nullable = false, length = 50)
    private String idSchedule;

    @Column(name = "group_Exam", length = 50)
    private String groupExam;

    @Column(name = "seats", nullable = false)
    private Short seats;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name = "ID_Schedule", referencedColumnName = "ID_Schedule", insertable = false, updatable = false)
    private Schedule schedule;

    @ManyToOne
    @JoinColumn(name = "ID_Semester", referencedColumnName = "ID_Semester", insertable = false, updatable = false)
    private Semester semester;

    /**
     * Constructor
     */
    public DateExam() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setIdSemester(String idSemester) {
        this.idSemester = idSemester;
    }

    public String getIdSemester() {
        return this.idSemester;
    }


    public void setIdSchedule(String idSchedule) {
        this.idSchedule = idSchedule;
    }

    public String getIdSchedule() {
        return this.idSchedule;
    }

    public void setGroupExam(String groupExam) {
        this.groupExam = groupExam;
    }

    public String getGroupExam() {
        return this.groupExam;
    }

    public void setSeats(Short seats) {
        this.seats = seats;
    }

    public Short getSeats() {
        return this.seats;
    }

    // --- GETTERS FOR LINKS
    public Schedule getSchedule() {
        return this.schedule;
    }

    public Semester getSemester() {
        return this.semester;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(id);
        sb.append("|");
        sb.append(idSemester);
        sb.append("|");
        sb.append(idSchedule);
        sb.append("|");
        sb.append(groupExam);
        sb.append("|");
        sb.append(seats);
        return sb.toString();
    }

}
