/*
 * Created on 2022-03-29 ( 21:59:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persitence.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "ProfessorSchedule"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Professor_Schedule", schema="dbo", catalog = "${bezkoder.app.databaseName}")
@IdClass(ProfessorScheduleId.class)
public class ProfessorSchedule implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_Semester", nullable=false, length=50)
    private String     idSemester ;

    @Id
    @Column(name="ID_Schedule", nullable=false, length=50)
    private String     idSchedule ;

    @Id
    @Column(name="ID_Professor", nullable=false, length=50)
    private String     idProfessor ;

    //--- ENTITY DATA FIELDS 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="ID_Schedule", referencedColumnName="ID_Schedule", insertable=false, updatable=false)
    private Schedule   schedule ; 

    @ManyToOne
    @JoinColumn(name="ID_Professor", referencedColumnName="ID_Professor", insertable=false, updatable=false)
    private Professor  professor ; 

    @ManyToOne
    @JoinColumn(name="ID_Semester", referencedColumnName="ID_Semester", insertable=false, updatable=false)
    private Semester   semester ; 


    /**
     * Constructor
     */
    public ProfessorSchedule() {
		super();
    }
    
    public ProfessorSchedule(String idSemester, String idSchedule, String idProfessor) {
        this.idSemester = idSemester;
        this.idSchedule = idSchedule;
        this.idProfessor = idProfessor;
    }

    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdSemester( String idSemester ) {
        this.idSemester = idSemester ;
    }
    public String getIdSemester() {
        return this.idSemester;
    }

    public void setIdSchedule( String idSchedule ) {
        this.idSchedule = idSchedule ;
    }
    public String getIdSchedule() {
        return this.idSchedule;
    }

    public void setIdProfessor( String idProfessor ) {
        this.idProfessor = idProfessor ;
    }
    public String getIdProfessor() {
        return this.idProfessor;
    }

    //--- GETTERS FOR LINKS
    public Schedule getSchedule() {
        return this.schedule;
    } 

    public Professor getProfessor() {
        return this.professor;
    } 

    public Semester getSemester() {
        return this.semester;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idSemester);
        sb.append("|");
        sb.append(idSchedule);
        sb.append("|");
        sb.append(idProfessor);
        return sb.toString(); 
    } 

}
