/*
 * Created on 2022-03-22 ( 22:26:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "AccountHasRole"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ACCOUNT_has_role", schema="dbo", catalog="Course_Registration" )
public class AccountHasRole implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_ACCOUNT", nullable=false, length=50)
    private String     idAccount ;

    //--- ENTITY DATA FIELDS 
    @Column(name="ID_Role", nullable=false, length=2)
    private String     idRole ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name="ID_ACCOUNT", referencedColumnName="ID_ACCOUNT", insertable=false, updatable=false)
    private Account    account ; 

    @ManyToOne
    @JoinColumn(name="ID_Role", referencedColumnName="ID_Role", insertable=false, updatable=false)
    private Role       role ; 


    /**
     * Constructor
     */
    public AccountHasRole() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdAccount( String idAccount ) {
        this.idAccount = idAccount ;
    }
    public String getIdAccount() {
        return this.idAccount;
    }

    public void setIdRole( String idRole ) {
        this.idRole = idRole ;
    }
    public String getIdRole() {
        return this.idRole;
    }

    //--- GETTERS FOR LINKS
    public Account getAccount() {
        return this.account;
    } 

    public Role getRole() {
        return this.role;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idAccount);
        sb.append("|");
        sb.append(idRole);
        return sb.toString(); 
    } 

}
