/*
 * Created on 2022-03-22 ( 22:26:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Account"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ACCOUNT", schema="dbo", catalog="Course_Registration" )
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_ACCOUNT", nullable=false, length=50)
    private String     idAccount ;

    //--- ENTITY DATA FIELDS 
    @Column(name="email", nullable=false, length=50)
    private String     email ;

    @Column(name="password", nullable=false, length=255)
    private String     password ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne(mappedBy="account")
    private Student    student ; 

    @OneToOne(mappedBy="account")
    private PasswordResetToken passwordResetToken ; 

    @OneToOne(mappedBy="account")
    private VerificationToken verificationToken ; 

    @OneToMany(mappedBy="account")
    private List<RefreshToken> listOfRefreshToken ; 

    @OneToOne(mappedBy="account")
    private AccountDetail accountDetail ; 

    @OneToOne(mappedBy="account")
    private AccountHasRole accountHasRole ; 

    @OneToOne(mappedBy="account")
    private Professor  professor ; 


    /**
     * Constructor
     */
    public Account() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdAccount( String idAccount ) {
        this.idAccount = idAccount ;
    }
    public String getIdAccount() {
        return this.idAccount;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    //--- GETTERS FOR LINKS
    public Student getStudent() {
        return this.student;
    } 

    public PasswordResetToken getPasswordResetToken() {
        return this.passwordResetToken;
    } 

    public VerificationToken getVerificationToken() {
        return this.verificationToken;
    } 

    public List<RefreshToken> getListOfRefreshToken() {
        return this.listOfRefreshToken;
    } 

    public AccountDetail getAccountDetail() {
        return this.accountDetail;
    } 

    public AccountHasRole getAccountHasRole() {
        return this.accountHasRole;
    } 

    public Professor getProfessor() {
        return this.professor;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idAccount);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 

}
