/*
 * Created on 2022-03-19 ( 10:13:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "ResetToken"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="reset_token", schema="dbo", catalog="MvcMovieContext" )
public class ResetToken implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="reset_token_content", length=2147483647)
    private String     resetTokenContent ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reset_token_expires")
    private Date       resetTokenExpires ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="password_reset")
    private Date       passwordReset ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne(mappedBy="resetToken")
    private Account    listOfAccount ; 


    /**
     * Constructor
     */
    public ResetToken() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setResetTokenContent( String resetTokenContent ) {
        this.resetTokenContent = resetTokenContent ;
    }
    public String getResetTokenContent() {
        return this.resetTokenContent;
    }

    public void setResetTokenExpires( Date resetTokenExpires ) {
        this.resetTokenExpires = resetTokenExpires ;
    }
    public Date getResetTokenExpires() {
        return this.resetTokenExpires;
    }

    public void setPasswordReset( Date passwordReset ) {
        this.passwordReset = passwordReset ;
    }
    public Date getPasswordReset() {
        return this.passwordReset;
    }

    //--- GETTERS FOR LINKS
    public Account getListOfAccount() {
        return this.listOfAccount;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(resetTokenContent);
        sb.append("|");
        sb.append(resetTokenExpires);
        sb.append("|");
        sb.append(passwordReset);
        return sb.toString(); 
    } 

}
