/*
 * Created on 2022-03-22 ( 22:26:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Role"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Role", schema="dbo", catalog="Course_Registration" )
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_Role", nullable=false, length=2)
    private String     idRole ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Name_Role", nullable=false, length=50)
    private String     nameRole ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="role")
    private List<AccountHasRole> listOfAccountHasRole ; 

    @OneToMany(mappedBy="role")
    private List<Privilege> listOfPrivilege ; 


    /**
     * Constructor
     */
    public Role() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdRole( String idRole ) {
        this.idRole = idRole ;
    }
    public String getIdRole() {
        return this.idRole;
    }

    public void setNameRole( String nameRole ) {
        this.nameRole = nameRole ;
    }
    public String getNameRole() {
        return this.nameRole;
    }

    //--- GETTERS FOR LINKS
    public List<AccountHasRole> getListOfAccountHasRole() {
        return this.listOfAccountHasRole;
    } 

    public List<Privilege> getListOfPrivilege() {
        return this.listOfPrivilege;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idRole);
        sb.append("|");
        sb.append(nameRole);
        return sb.toString(); 
    } 

}
