/*
 * Created on 2022-03-19 ( 10:13:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "RolesOfUser"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="roles_of_user", schema="dbo", catalog="MvcMovieContext" )
public class RolesOfUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="rolesOfUser")
    private List<Role> listOfRole ; 

    @OneToOne(mappedBy="rolesOfUser")
    private Account    listOfAccount ; 


    /**
     * Constructor
     */
    public RolesOfUser() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //--- GETTERS FOR LINKS
    public List<Role> getListOfRole() {
        return this.listOfRole;
    } 

    public Account getListOfAccount() {
        return this.listOfAccount;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        return sb.toString(); 
    } 

}
