/*
 * Created on 2022-03-22 ( 22:26:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package code.backend.persistent.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "SubPass"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Sub_Pass", schema="dbo", catalog="Course_Registration" )
@IdClass(SubPassId.class)
public class SubPass implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ID_Semester", nullable=false, length=50)
    private String     idSemester ;

    @Id
    @Column(name="ID_Course", nullable=false, length=50)
    private String     idCourse ;

    @Id
    @Column(name="ID_Student", nullable=false, length=50)
    private String     idStudent ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Score", nullable=false)
    private Double     score ;

    @Column(name="Score_System_4", nullable=false)
    private Double     scoreSystem4 ;

    @Column(name="Rated", nullable=false, length=10)
    private String     rated ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="ID_Course", referencedColumnName="ID_Course", insertable=false, updatable=false)
    private Course     course ; 

    @ManyToOne
    @JoinColumn(name="ID_Student", referencedColumnName="ID_Student", insertable=false, updatable=false)
    private Student    student ; 

    @ManyToOne
    @JoinColumn(name="ID_Semester", referencedColumnName="ID_Semester", insertable=false, updatable=false)
    private Semester   semester ; 


    /**
     * Constructor
     */
    public SubPass() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdSemester( String idSemester ) {
        this.idSemester = idSemester ;
    }
    public String getIdSemester() {
        return this.idSemester;
    }

    public void setIdCourse( String idCourse ) {
        this.idCourse = idCourse ;
    }
    public String getIdCourse() {
        return this.idCourse;
    }

    public void setIdStudent( String idStudent ) {
        this.idStudent = idStudent ;
    }
    public String getIdStudent() {
        return this.idStudent;
    }

    public void setScore( Double score ) {
        this.score = score ;
    }
    public Double getScore() {
        return this.score;
    }

    public void setScoreSystem4( Double scoreSystem4 ) {
        this.scoreSystem4 = scoreSystem4 ;
    }
    public Double getScoreSystem4() {
        return this.scoreSystem4;
    }

    public void setRated( String rated ) {
        this.rated = rated ;
    }
    public String getRated() {
        return this.rated;
    }

    //--- GETTERS FOR LINKS
    public Course getCourse() {
        return this.course;
    } 

    public Student getStudent() {
        return this.student;
    } 

    public Semester getSemester() {
        return this.semester;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idSemester);
        sb.append("|");
        sb.append(idCourse);
        sb.append("|");
        sb.append(idStudent);
        sb.append("|");
        sb.append(score);
        sb.append("|");
        sb.append(scoreSystem4);
        sb.append("|");
        sb.append(rated);
        return sb.toString(); 
    } 

}
